// VocabDaily — Idioms, Phrasal Verbs & Collocations
window.IDIOMS_DATA = {
    idioms: [
        { phrase: "break the ice", meaning: "Start a conversation in an awkward situation", example: "She told a joke to break the ice at the meeting.", category: "everyday" },
        { phrase: "piece of cake", meaning: "Something very easy to do", example: "The test was a piece of cake!", category: "food" },
        { phrase: "hit the nail on the head", meaning: "Describe exactly what is causing a problem", example: "You hit the nail on the head with that analysis.", category: "everyday" },
        { phrase: "under the weather", meaning: "Feeling sick or unwell", example: "I'm feeling a bit under the weather today.", category: "weather" },
        { phrase: "bite the bullet", meaning: "Endure a painful situation bravely", example: "I bit the bullet and went to the dentist.", category: "everyday" },
        { phrase: "cost an arm and a leg", meaning: "Be very expensive", example: "That designer bag cost an arm and a leg.", category: "body" },
        { phrase: "let the cat out of the bag", meaning: "Reveal a secret accidentally", example: "She let the cat out of the bag about the surprise party.", category: "animals" },
        { phrase: "once in a blue moon", meaning: "Very rarely", example: "He only visits once in a blue moon.", category: "weather" },
        { phrase: "spill the beans", meaning: "Reveal secret information", example: "Come on, spill the beans! What happened?", category: "food" },
        { phrase: "beat around the bush", meaning: "Avoid talking about the main topic", example: "Stop beating around the bush and tell me the truth.", category: "everyday" },
        { phrase: "burn the midnight oil", meaning: "Work late into the night", example: "She burned the midnight oil to finish her thesis.", category: "business" },
        { phrase: "cry over spilt milk", meaning: "Waste time worrying about past mistakes", example: "What's done is done — no use crying over spilt milk.", category: "food" },
        { phrase: "the elephant in the room", meaning: "An obvious problem no one wants to discuss", example: "His poor performance was the elephant in the room.", category: "animals" },
        { phrase: "get cold feet", meaning: "Become nervous and hesitant", example: "She got cold feet before the wedding.", category: "body" },
        { phrase: "kill two birds with one stone", meaning: "Achieve two things with one action", example: "By cycling to work, I kill two birds with one stone — exercise and commute.", category: "animals" },
        { phrase: "see eye to eye", meaning: "Agree with someone", example: "We don't always see eye to eye on politics.", category: "body" },
        { phrase: "the ball is in your court", meaning: "It's your turn to make a decision", example: "I've made my offer. The ball is in your court.", category: "everyday" },
        { phrase: "through thick and thin", meaning: "Through good and bad times", example: "She's been my friend through thick and thin.", category: "emotions" },
        { phrase: "when pigs fly", meaning: "Something that will never happen", example: "He'll clean his room when pigs fly.", category: "animals" },
        { phrase: "barking up the wrong tree", meaning: "Looking in the wrong place or accusing the wrong person", example: "If you think I did it, you're barking up the wrong tree.", category: "animals" },
        { phrase: "blessing in disguise", meaning: "Something good that initially seemed bad", example: "Losing that job was a blessing in disguise.", category: "everyday" },
        { phrase: "break a leg", meaning: "Good luck (especially in performance)", example: "You're performing tonight? Break a leg!", category: "body" },
        { phrase: "cut to the chase", meaning: "Get to the point without wasting time", example: "Let me cut to the chase — we need more funding.", category: "business" },
        { phrase: "go the extra mile", meaning: "Make more effort than expected", example: "She always goes the extra mile for her clients.", category: "business" },
        { phrase: "hang in there", meaning: "Don't give up; be patient", example: "I know it's tough, but hang in there.", category: "emotions" },
        { phrase: "it takes two to tango", meaning: "Both parties are responsible", example: "Don't just blame him — it takes two to tango.", category: "everyday" },
        { phrase: "on cloud nine", meaning: "Extremely happy", example: "She's been on cloud nine since getting the promotion.", category: "emotions" },
        { phrase: "pull someone's leg", meaning: "Joke with someone", example: "Relax, I'm just pulling your leg!", category: "body" },
        { phrase: "a penny for your thoughts", meaning: "What are you thinking about?", example: "You look deep in thought — a penny for your thoughts?", category: "everyday" },
        { phrase: "actions speak louder than words", meaning: "What you do matters more than what you say", example: "He keeps promising, but actions speak louder than words.", category: "everyday" },
        { phrase: "back to the drawing board", meaning: "Start over after a failure", example: "The plan failed — back to the drawing board.", category: "business" },
    ],

    phrasalVerbs: [
        { verb: "break down", meaning: "Stop functioning / analyze in detail", example: "My car broke down on the highway.", separable: false },
        { verb: "bring up", meaning: "Mention a topic / raise a child", example: "She brought up an interesting point.", separable: true },
        { verb: "call off", meaning: "Cancel", example: "They called off the meeting due to the storm.", separable: true },
        { verb: "carry on", meaning: "Continue doing something", example: "Carry on with your work, I'll wait.", separable: false },
        { verb: "check out", meaning: "Investigate / leave a hotel", example: "You should check out this new restaurant.", separable: true },
        { verb: "come across", meaning: "Find by chance", example: "I came across an old photo in the attic.", separable: false },
        { verb: "cut back", meaning: "Reduce the amount of something", example: "We need to cut back on expenses.", separable: false },
        { verb: "figure out", meaning: "Understand or solve something", example: "I can't figure out this math problem.", separable: true },
        { verb: "get along", meaning: "Have a good relationship", example: "Do you get along with your coworkers?", separable: false },
        { verb: "get over", meaning: "Recover from something", example: "It took her months to get over the breakup.", separable: false },
        { verb: "give up", meaning: "Stop trying / surrender", example: "Never give up on your dreams.", separable: true },
        { verb: "go through", meaning: "Experience / examine carefully", example: "She went through a difficult time last year.", separable: false },
        { verb: "hang out", meaning: "Spend time casually", example: "Want to hang out this weekend?", separable: false },
        { verb: "hold on", meaning: "Wait / grip tightly", example: "Hold on, let me check that for you.", separable: false },
        { verb: "keep up", meaning: "Maintain the same speed or level", example: "She walks so fast, I can't keep up.", separable: false },
        { verb: "let down", meaning: "Disappoint someone", example: "I feel like I've let you down.", separable: true },
        { verb: "look after", meaning: "Take care of", example: "Can you look after my cat this weekend?", separable: false },
        { verb: "look forward to", meaning: "Be excited about something future", example: "I look forward to meeting you.", separable: false },
        { verb: "make up", meaning: "Invent / reconcile / apply cosmetics", example: "They had a fight but made up quickly.", separable: true },
        { verb: "pick up", meaning: "Lift / collect / learn casually", example: "I picked up some Spanish while traveling.", separable: true },
        { verb: "put off", meaning: "Postpone", example: "Stop putting off your homework!", separable: true },
        { verb: "run into", meaning: "Meet by chance", example: "I ran into my old teacher at the store.", separable: false },
        { verb: "set up", meaning: "Arrange / establish", example: "Let's set up a meeting for next week.", separable: true },
        { verb: "show up", meaning: "Arrive / appear", example: "He didn't show up to the party.", separable: false },
        { verb: "take off", meaning: "Remove / leave quickly / become successful", example: "The plane is about to take off.", separable: true },
        { verb: "turn down", meaning: "Reject / reduce volume", example: "She turned down the job offer.", separable: true },
        { verb: "work out", meaning: "Exercise / find a solution", example: "Things will work out in the end.", separable: false },
    ],

    collocations: [
        { words: "make a decision", meaning: "Decide something", example: "We need to make a decision by Friday.", category: "make/do" },
        { words: "do homework", meaning: "Complete school assignments", example: "Have you done your homework yet?", category: "make/do" },
        { words: "make progress", meaning: "Move forward toward a goal", example: "We're making progress on the project.", category: "make/do" },
        { words: "do damage", meaning: "Cause harm", example: "The storm did a lot of damage.", category: "make/do" },
        { words: "make an effort", meaning: "Try hard", example: "Please make an effort to arrive on time.", category: "make/do" },
        { words: "strong coffee", meaning: "Coffee with intense flavor", example: "I need a strong coffee this morning.", category: "strong/weak" },
        { words: "heavy rain", meaning: "Intense rainfall", example: "There was heavy rain all weekend.", category: "adjective+noun" },
        { words: "take a shower", meaning: "Wash yourself in a shower", example: "I take a shower every morning.", category: "verb+noun" },
        { words: "pay attention", meaning: "Focus and listen carefully", example: "Please pay attention to the instructions.", category: "verb+noun" },
        { words: "catch a cold", meaning: "Become ill with a cold", example: "I caught a cold from my coworker.", category: "verb+noun" },
        { words: "break a promise", meaning: "Fail to do what you promised", example: "I never break a promise.", category: "verb+noun" },
        { words: "keep a secret", meaning: "Not tell anyone", example: "Can you keep a secret?", category: "verb+noun" },
        { words: "lose track", meaning: "Forget to monitor something", example: "I lost track of time reading.", category: "verb+noun" },
        { words: "big deal", meaning: "Something very important", example: "Getting into Harvard is a big deal.", category: "adjective+noun" },
        { words: "deep breath", meaning: "A long, full breath", example: "Take a deep breath and relax.", category: "adjective+noun" },
        { words: "fast asleep", meaning: "Sleeping very deeply", example: "The baby is fast asleep.", category: "adjective+noun" },
        { words: "wide awake", meaning: "Completely awake", example: "I was wide awake at 3 AM.", category: "adjective+noun" },
        { words: "common sense", meaning: "Basic practical judgment", example: "Use your common sense!", category: "adjective+noun" },
        { words: "mixed feelings", meaning: "Conflicting emotions", example: "I have mixed feelings about the move.", category: "adjective+noun" },
        { words: "last resort", meaning: "Final option when all else fails", example: "Surgery should be the last resort.", category: "adjective+noun" },
    ]
};
